services:
  postgres:
    image: postgres:15
    container_name: person-postgres
    environment:
      POSTGRES_DB: persondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - checklist-network

  person-service:
    build: .
    container_name: person-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/persondb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - checklist-network
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  checklist-network:
    external: true