//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.10 at 02:26:07 PM MSK 
//


package ru.itmo.person_service.soap.dto;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ColorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="ColorType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="GREEN"/&gt;
 *     &lt;enumeration value="BLUE"/&gt;
 *     &lt;enumeration value="ORANGE"/&gt;
 *     &lt;enumeration value="BROWN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ColorType")
@XmlEnum
public enum ColorType {

    GREEN,
    BLUE,
    ORANGE,
    BROWN;

    public String value() {
        return name();
    }

    public static ColorType fromValue(String v) {
        return valueOf(v);
    }

}
