//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.24 at 02:35:48 PM MSK 
//


package ru.itmo.person_service.soap.dto;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.itmo.person_service.soap.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetPersonByIdResponse_QNAME = new QName("http://itmo.ru/person-service", "getPersonByIdResponse");
    private final static QName _CreatePersonResponse_QNAME = new QName("http://itmo.ru/person-service", "createPersonResponse");
    private final static QName _UpdatePersonResponse_QNAME = new QName("http://itmo.ru/person-service", "updatePersonResponse");
    private final static QName _SearchPersonsRequest_QNAME = new QName("http://itmo.ru/person-service", "searchPersonsRequest");
    private final static QName _SearchPersonsResponse_QNAME = new QName("http://itmo.ru/person-service", "searchPersonsResponse");
    private final static QName _FindPersonWithLongestNameResponse_QNAME = new QName("http://itmo.ru/person-service", "findPersonWithLongestNameResponse");
    private final static QName _GetHairColorStatsResponse_QNAME = new QName("http://itmo.ru/person-service", "getHairColorStatsResponse");
    private final static QName _GetNationalityStatsResponse_QNAME = new QName("http://itmo.ru/person-service", "getNationalityStatsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.itmo.person_service.soap.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPersonByIdRequest }
     * 
     */
    public GetPersonByIdRequest createGetPersonByIdRequest() {
        return new GetPersonByIdRequest();
    }

    /**
     * Create an instance of {@link PersonResponse }
     * 
     */
    public PersonResponse createPersonResponse() {
        return new PersonResponse();
    }

    /**
     * Create an instance of {@link CreatePersonRequest }
     * 
     */
    public CreatePersonRequest createCreatePersonRequest() {
        return new CreatePersonRequest();
    }

    /**
     * Create an instance of {@link PersonRequest }
     * 
     */
    public PersonRequest createPersonRequest() {
        return new PersonRequest();
    }

    /**
     * Create an instance of {@link UpdatePersonRequest }
     * 
     */
    public UpdatePersonRequest createUpdatePersonRequest() {
        return new UpdatePersonRequest();
    }

    /**
     * Create an instance of {@link DeletePersonRequest }
     * 
     */
    public DeletePersonRequest createDeletePersonRequest() {
        return new DeletePersonRequest();
    }

    /**
     * Create an instance of {@link DeletePersonResponse }
     * 
     */
    public DeletePersonResponse createDeletePersonResponse() {
        return new DeletePersonResponse();
    }

    /**
     * Create an instance of {@link SearchCriteria }
     * 
     */
    public SearchCriteria createSearchCriteria() {
        return new SearchCriteria();
    }

    /**
     * Create an instance of {@link PagedResponse }
     * 
     */
    public PagedResponse createPagedResponse() {
        return new PagedResponse();
    }

    /**
     * Create an instance of {@link CountPersonsRequest }
     * 
     */
    public CountPersonsRequest createCountPersonsRequest() {
        return new CountPersonsRequest();
    }

    /**
     * Create an instance of {@link CountPersonsResponse }
     * 
     */
    public CountPersonsResponse createCountPersonsResponse() {
        return new CountPersonsResponse();
    }

    /**
     * Create an instance of {@link PersonExistsRequest }
     * 
     */
    public PersonExistsRequest createPersonExistsRequest() {
        return new PersonExistsRequest();
    }

    /**
     * Create an instance of {@link PersonExistsResponse }
     * 
     */
    public PersonExistsResponse createPersonExistsResponse() {
        return new PersonExistsResponse();
    }

    /**
     * Create an instance of {@link FindPersonWithLongestNameRequest }
     * 
     */
    public FindPersonWithLongestNameRequest createFindPersonWithLongestNameRequest() {
        return new FindPersonWithLongestNameRequest();
    }

    /**
     * Create an instance of {@link DeleteOneByHairColorRequest }
     * 
     */
    public DeleteOneByHairColorRequest createDeleteOneByHairColorRequest() {
        return new DeleteOneByHairColorRequest();
    }

    /**
     * Create an instance of {@link DeleteOneByHairColorResponse }
     * 
     */
    public DeleteOneByHairColorResponse createDeleteOneByHairColorResponse() {
        return new DeleteOneByHairColorResponse();
    }

    /**
     * Create an instance of {@link FindPersonsByNationalityLessThanRequest }
     * 
     */
    public FindPersonsByNationalityLessThanRequest createFindPersonsByNationalityLessThanRequest() {
        return new FindPersonsByNationalityLessThanRequest();
    }

    /**
     * Create an instance of {@link FindPersonsByNationalityLessThanResponse }
     * 
     */
    public FindPersonsByNationalityLessThanResponse createFindPersonsByNationalityLessThanResponse() {
        return new FindPersonsByNationalityLessThanResponse();
    }

    /**
     * Create an instance of {@link GetHairColorStatsRequest }
     * 
     */
    public GetHairColorStatsRequest createGetHairColorStatsRequest() {
        return new GetHairColorStatsRequest();
    }

    /**
     * Create an instance of {@link StatsResponse }
     * 
     */
    public StatsResponse createStatsResponse() {
        return new StatsResponse();
    }

    /**
     * Create an instance of {@link GetNationalityStatsRequest }
     * 
     */
    public GetNationalityStatsRequest createGetNationalityStatsRequest() {
        return new GetNationalityStatsRequest();
    }

    /**
     * Create an instance of {@link Coordinates }
     * 
     */
    public Coordinates createCoordinates() {
        return new Coordinates();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link PageRequest }
     * 
     */
    public PageRequest createPageRequest() {
        return new PageRequest();
    }

    /**
     * Create an instance of {@link Sort }
     * 
     */
    public Sort createSort() {
        return new Sort();
    }

    /**
     * Create an instance of {@link FilterCondition }
     * 
     */
    public FilterCondition createFilterCondition() {
        return new FilterCondition();
    }

    /**
     * Create an instance of {@link MapEntry }
     * 
     */
    public MapEntry createMapEntry() {
        return new MapEntry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PersonResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://itmo.ru/person-service", name = "getPersonByIdResponse")
    public JAXBElement<PersonResponse> createGetPersonByIdResponse(PersonResponse value) {
        return new JAXBElement<PersonResponse>(_GetPersonByIdResponse_QNAME, PersonResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PersonResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://itmo.ru/person-service", name = "createPersonResponse")
    public JAXBElement<PersonResponse> createCreatePersonResponse(PersonResponse value) {
        return new JAXBElement<PersonResponse>(_CreatePersonResponse_QNAME, PersonResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PersonResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://itmo.ru/person-service", name = "updatePersonResponse")
    public JAXBElement<PersonResponse> createUpdatePersonResponse(PersonResponse value) {
        return new JAXBElement<PersonResponse>(_UpdatePersonResponse_QNAME, PersonResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchCriteria }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SearchCriteria }{@code >}
     */
    @XmlElementDecl(namespace = "http://itmo.ru/person-service", name = "searchPersonsRequest")
    public JAXBElement<SearchCriteria> createSearchPersonsRequest(SearchCriteria value) {
        return new JAXBElement<SearchCriteria>(_SearchPersonsRequest_QNAME, SearchCriteria.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PagedResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PagedResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://itmo.ru/person-service", name = "searchPersonsResponse")
    public JAXBElement<PagedResponse> createSearchPersonsResponse(PagedResponse value) {
        return new JAXBElement<PagedResponse>(_SearchPersonsResponse_QNAME, PagedResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PersonResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://itmo.ru/person-service", name = "findPersonWithLongestNameResponse")
    public JAXBElement<PersonResponse> createFindPersonWithLongestNameResponse(PersonResponse value) {
        return new JAXBElement<PersonResponse>(_FindPersonWithLongestNameResponse_QNAME, PersonResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StatsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://itmo.ru/person-service", name = "getHairColorStatsResponse")
    public JAXBElement<StatsResponse> createGetHairColorStatsResponse(StatsResponse value) {
        return new JAXBElement<StatsResponse>(_GetHairColorStatsResponse_QNAME, StatsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StatsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://itmo.ru/person-service", name = "getNationalityStatsResponse")
    public JAXBElement<StatsResponse> createGetNationalityStatsResponse(StatsResponse value) {
        return new JAXBElement<StatsResponse>(_GetNationalityStatsResponse_QNAME, StatsResponse.class, null, value);
    }

}
