//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.24 at 02:35:48 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://itmo.ru/person-service", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.itmo.person_service.soap.dto;
